import { test, expect } from '@playwright/test'

test('offline budget, merchant rule, transaction extras, alerts and savings goal', async ({ page, request }) => {
  test.skip(process.env.LEDGERLIGHT_E2E_PLAID === 'sandbox', 'Synthetic offline data only')
  await page.route('**/*', route => new URL(route.request().url()).hostname === '127.0.0.1' ? route.continue() : route.abort())
  expect((await request.post('/api/plaid/exchange', { data: { public_token: 'public-synthetic-ledgerlight' } })).ok()).toBeTruthy()
  expect((await request.post('/api/sync')).ok()).toBeTruthy()
  await page.goto('/#/budgets')
  await page.getByLabel('Budget category').fill('ENTERTAINMENT')
  await page.getByLabel('Monthly limit').fill('24')
  await page.getByRole('button', { name: 'Set budget' }).click()
  await expect(page.getByText('Spent 12.00 of 24.00 · 50.0% · Remaining 12.00')).toBeVisible()

  await page.getByRole('link', { name: 'Rules', exact: true }).click()
  await page.getByLabel('Pattern', { exact: true }).fill('Synthetic Streaming')
  await page.getByLabel('Rule category').fill('Leisure')
  await expect(page.getByText('Matching transactions: 1')).toBeVisible()
  await page.getByRole('button', { name: 'Add rule', exact: true }).click()
  await expect(page.getByText('Rule saved and applied.')).toBeVisible()
  await page.getByRole('link', { name: 'Transactions', exact: true }).click()
  const row = page.getByRole('row').filter({ has: page.getByRole('cell', { name: 'Synthetic Streaming', exact: true }) })
  await expect(row.getByRole('cell', { name: 'Leisure', exact: true })).toBeVisible()
  await row.getByText('Edit transaction', { exact: true }).click()
  await row.getByLabel('Note', { exact: true }).fill('Synthetic subscription note')
  await row.getByRole('button', { name: 'Save note' }).click()
  await expect(row.getByText('Note: Synthetic subscription note')).toBeVisible()
  await row.getByLabel('Tags (comma separated)').fill('review, subscription')
  await row.getByRole('button', { name: 'Add tags' }).click()
  await expect(row.getByText('Tags: review, subscription')).toBeVisible()
  await row.getByLabel('Split parts').fill('Leisure=-7\nHome=-4')
  await row.getByRole('button', { name: 'Save split' }).click()
  await expect(row.getByRole('alert')).toContainText('sum exactly')
  await row.getByLabel('Split parts').fill('Leisure=-7\nHome=-5')
  await row.getByRole('button', { name: 'Save split' }).click()
  await expect(row.getByText('Splits: Leisure: -7.00; Home: -5.00')).toBeVisible()
  await row.getByRole('button', { name: 'Hide transaction', exact: true }).click()
  await expect(row.getByText('Hidden', { exact: true })).toBeVisible()
  await row.getByRole('button', { name: 'Unhide transaction', exact: true }).click()
  await expect(row.getByText('Hidden', { exact: true })).toHaveCount(0)
  await page.reload()
  await expect(row.getByText('Splits: Leisure: -7.00; Home: -5.00')).toBeVisible()

  await page.getByRole('link', { name: 'Bills', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Synthetic Streaming' })).toBeVisible()
  await page.getByRole('link', { name: 'Settings', exact: true }).click()
  await page.getByLabel('Low balance threshold', { exact: true }).fill('2600')
  await page.getByRole('button', { name: 'Save thresholds' }).click()
  const dismiss = page.getByRole('button', { name: 'Dismiss Low balance: Synthetic Checking', exact: true })
  await expect(dismiss).toBeVisible()
  await dismiss.click()
  await expect(dismiss).toHaveCount(0)
  await page.getByRole('button', { name: 'Refresh alerts' }).click()
  await expect(dismiss).toHaveCount(0)

  await page.getByRole('link', { name: 'Goals', exact: true }).click()
  await page.getByLabel('Goal name', { exact: true }).fill('Synthetic Emergency Fund')
  await page.getByLabel('Target amount', { exact: true }).fill('5000')
  await page.getByRole('checkbox', { name: 'Synthetic Checking', exact: true }).check()
  await page.getByRole('button', { name: 'Add goal' }).click()
  await expect(page.getByRole('heading', { name: 'Synthetic Emergency Fund' })).toBeVisible()
  await expect(page.getByText('Progress 2,500.00 of 5,000.00 · 50.0% · Remaining 2,500.00')).toBeVisible()
  await page.reload()
  await expect(page.getByText('Progress 2,500.00 of 5,000.00 · 50.0% · Remaining 2,500.00')).toBeVisible()
})
